import type { Metadata } from 'next';
import { Rammetto_One } from 'next/font/google';
import './globals.css';

const Rammetto = Rammetto_One({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' data-theme='light'>
      <body className={Rammetto.className}>{children}</body>
    </html>
  );
}
