import type { Metadata } from 'next';
import { Paytone_One } from 'next/font/google';
import './globals.css';

const Paytone = Paytone_One({
  subsets: ['latin'],
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Studio Mi²C',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja' data-theme='light'>
      <body className={Paytone.className}>{children}</body>
    </html>
  );
}
